name: Lint

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    env:
      NODE_VERSION: 12

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ env.NODE_VERSION }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-${{ env.NODE_VERSION }}-

      - name: Install dependencies
        run: npm install

      - name: Run linters
        uses: Quartz/lint-action@v1
        with:
          github_token: ${{ secrets.github_token }}
          auto_fix: true
          eslint: true
          eslint_args: "--ext .js,.jsx,.ts,.tsx --ignore-path .gitignore --ignore-pattern *.d.ts",
          stylelint: true
          stylelint_args: "--ignore-path .gitignore"
